name: first

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs: 
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: tar
          run: tar cvf all.tar *
        - name: Upload artifact for linux
          uses: actions/upload-artifact@v1.0.0
          with:
            name: all.tar
            path: ./${{ env.FILE_NAME }}
